### ISSUE TITLE
Missing commas in output causing crashes

### ISSUE THREAD

**Issue by INTRCPTR** [rei2hu/swayblocks#1] opened 2018-09-25 17:48 UTC
I installed swayblocks using the AUR on arch linux. It loaded the blocks properly for a couple seconds then the text is replaced by [invalid i3bar json].

**Comment by rei2hu** [comment] 2018-09-25 19:44
Could you run the `swayblocks` command in a console and share the output after a few seconds? e.g.
```
{"version":1,"click_events":true}
[
[{"separator_block_width":"10","separator":"false","name":"~/.config/swayblocks/scripts/cmus","full_text":"","color":"#44ffff"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/cmus","full_text":"","color":"#44ffff"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","full_text":"🔊 23%"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","full_text":"📡 192.168.1.6","color":"#44ff44","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","full_text":"📶 45.0","color":"#AFFF00","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/brightness","full_text":"💡 10%"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/battery","full_text":"🔋 (+) ▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▯","color":"#0FFF00"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","full_text":"Tue Sep 25, 2018 14:42:06","color":"#ff44ff"}]
[{"separator_block_width":"10","separator":"false","name":"~/.config/swayblocks/scripts/cmus","full_text":"","color":"#44ffff"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/cmus","full_text":"","color":"#44ffff"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","full_text":"🔊 23%"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","full_text":"📡 192.168.1.6","color":"#44ff44","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","full_text":"📶 45.0","color":"#AFFF00","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/brightness","full_text":"💡 10%"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/battery","full_text":"🔋 (+) ▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▯","color":"#0FFF00"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","full_text":"Tue Sep 25, 2018 14:42:07","color":"#ff44ff"}]
[{"separator_block_width":"10","separator":"false","name":"~/.config/swayblocks/scripts/cmus","full_text":"","color":"#44ffff"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/cmus","full_text":"","color":"#44ffff"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","full_text":"🔊 23%"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","full_text":"📡 192.168.1.6","color":"#44ff44","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","full_text":"📶 45.0","color":"#AFFF00","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/brightness","full_text":"💡 10%"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/battery","full_text":"🔋 (+) ▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▯","color":"#0FFF00"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","full_text":"Tue Sep 25, 2018 14:42:08","color":"#ff44ff"}]
[{"separator_block_width":"10","separator":"false","name":"~/.config/swayblocks/scripts/cmus","full_text":"","color":"#44ffff"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/cmus","full_text":"","color":"#44ffff"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","full_text":"🔊 23%"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","full_text":"📡 192.168.1.6","color":"#44ff44","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","full_text":"📶 45.0","color":"#AFFF00","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/brightness","full_text":"💡 10%"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/battery","full_text":"🔋 (+) ▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▯","color":"#0FFF00"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","full_text":"Tue Sep 25, 2018 14:42:09","color":"#ff44ff"}]
```

**Comment by INTRCPTR** [comment] 2018-09-27 14:23
{"version":1,"click_events":true}
[
[{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/volume","full_text":"🔊  100%"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","full_text":"📡  127.0.1.1","color":"#ffff44","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","full_text":"📶  ","color":"#FF0000","border":"#333333"},{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/date","full_text":"Thu Sep 27, 2018 09:17:56","color":"#ff44ff"}]
I am still using the stock blocks and tried deleting some in a effort of trouble shooting.

**Comment by rei2hu** [comment] 2018-09-28 00:07
That output looks fine to me.

I am aware of one potential source of the problem which is that I don't end each array with commas but `sway version 1.0-alpha.5-145-ge86d99ac` hasn't given me any errors for that ever so I never bothered fixing it. I'll fix that now just in case, though, because it could possibly be the cause.

If that was the problem, the blocks should've loaded for however long the shortest block will update in (in this case 1 second for the date) and then after that time period, you would see the error message.

If that doesn't fix it I don't have any other guesses. One thing you might be able to do is intercept the json that's actually sent to `swaybar` with something along the lines of `cat /proc/$(pidof swaybar)/fd/5` which is just like running the command itself although if you do this your bar won't update and might error when you close out.

(I'm assuming you're using sway because of the error message, I never actually tested this on i3)

**Comment by rei2hu** [comment] 2018-09-29 06:35
I decided to update sway to `sway version 1.0-alpha.6-77-gdc01e884` and revert the comma fix as a test, and I encountered the error you got.

I looked at the commits for sway and noticed a few changes to swaybar which modified how clicks were being sent in addition to how the json is being read. The invalid json problem should be fixed by [this commit](https://github.com/rei2hu/swayblocks/commit/cf64e3505ed1cc51b91ac082602412c39dd94862) and click events should be fixed by [this commit](https://github.com/rei2hu/swayblocks/commit/345ef9198b83fcc1776dfc6e88d24ba008c9e16c).

Let me know if it's still not working.

(closing because I believe it's fixed)

**Comment by INTRCPTR** [comment] 2018-10-11 19:38
yes it is fixed thanks, sorry for not responding back

**Comment by ashnur** [comment] 2018-11-11 15:33
swayblocks output:
```
{"version":1,"click_events":true}
[15:33:13] [INFO] Starting swayblocks...
[
[15:33:13] [INFO] Timer message recieved 0
[{"separator_block_width":"10","separator":"false","name":"~/.config/swayblocks/scripts/cmus","instance":0,"full_text":"","color":"#44ffff"}{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/cmus","instance":1,"full_text":"","color":"#44ffff"},{"separator_block_width":"10","separator":"","name":"~/.config/swayblocks/scripts/wifi","instance":0,"full_text":"📡 192.168.0.79","color":"#44ff44","border":"#333333"}{"separator_block_width":25,"name":"~/.config/swayblocks/scripts/wifi","instance":1,"full_text":"📶 34.0","color":"#FFEE00","border":"#333333"}],
```
note the missing commas between the objects.

sway version 1.0-alpha.6-300-g103b7bc4 (Oct 18 2018, branch 'master')
swayblocks version  r45.9257a84-1 [installed] [1+] [0.54%] [14 Oct 2018]

config:
```
[
  %{
    :name => "~/.config/swayblocks/scripts/wifi",
    :time => 1000,
    :default => %{
      "separator_block_width" => 25
    }
  },
  %{
    :name => "~/.config/swayblocks/scripts/cmus",
    :time => 1000,
    :click => "~/.config/swayblocks/scripts/click/pause",
    :default => %{
      "separator_block_width" => 25,
      "color" => "#44ffff"
    }
  }
]
```

**Comment by rei2hu** [comment] 2018-11-11 16:15
Thanks for pointing this out. I think the latest commit 17f8773 will have fixed it.

**Comment by ashnur** [comment] 2018-11-11 17:57
I can confirm, that after I updated swayblocks to https://github.com/rei2hu/swayblocks/commit/17f877303555ea46bda67abcfa0a1ef774ec16a5 the problem was solved on my machine.

**Closed as completed** 2018-11-11 18:44 UTC
Labels: bug, fixed
